name: docker-build-push

on:
  push:
    branches:
      - "main"
    # 核心修改：添加 paths 过滤
    paths:
      - 'Dockerfile'      # 只有当根目录下的 Dockerfile 变动时才触发
      # - 'docker/**'     # 如果你的构建脚本在特定目录下，也可以加上目录
    tags:
      - 'v*'
  workflow_dispatch:      # 手动触发依然保留

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: 'docker.io'
      # 记得这里改成你自己的: <你的用户名>/<镜像名>
      IMAGE_NAME: yutouxiaozhuan/nav2-humble

    steps:
      # 1. 检出代码 (必须)
      - name: Checkout code
        uses: actions/checkout@v3

      # --- 删除掉了 Set up JDK 11 ---
      # --- 删除掉了 Build with Maven ---

      # 2. 登录 Docker Hub (必须)
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 提取元数据 (自动生成 tag)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      # 4. 构建并推送 (核心步骤)
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          # 确认你的 Dockerfile 就在根目录，如果不是，要改这里
          file: ./.devcontainer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
